# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

# There are lots of internals of Rattle want to test, but don't want to expose
- message: Module reused between components

# There are a few general modules that offer a complete interface,
# but only a subset is used here
- message:
  - name: Weeds exported
  - module: [General.Bilist, General.EscCodes, General.FileInfo]

# Module still in development
- message:
  - name: Weeds exported
  - module: Development.Rattle.Profile

# Enum where we only use some of the values externally
- message:
  - name: Weeds exported
  - identifier: Restartable
