build: off
cache: "c:\\sr -> appveyor.yml"

test_script:
- ps: Invoke-WebRequest 'https://github.com/ndmitchell/shake/releases/download/fsatrace-1/fsatrace.zip' -OutFile 'fsatrace.zip'
- 7z x fsatrace.zip
- fsatrace v - -- echo fsatrace works
- ps: Invoke-Expression (Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/neil/master/appveyor.ps1')
